# Generated by Django 5.2 on 2025-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producte', '0002_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='templates',
            field=models.ManyToManyField(blank=True, to='producte.producttemplate'),
        ),
    ]
