# Generated by Django 5.2 on 2025-04-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producte', '0003_alter_productcategory_templates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='cat_pare',
            new_name='pare',
        ),
    ]
